"""add custom fee fields to creators

Revision ID: 0e7704fc4b29
Revises: ae991a3ef8ef
Create Date: 2026-02-14 20:13:11.514814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e7704fc4b29'
down_revision = 'ae991a3ef8ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_fixed_fee', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('custom_percentage_fee', sa.Numeric(precision=10, scale=4), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.drop_column('custom_percentage_fee')
        batch_op.drop_column('custom_fixed_fee')

    # ### end Alembic commands ###
