"""add is_blocked to creators

Revision ID: 19efe4a14065
Revises: fb0f6bf7e0e0
Create Date: 2026-02-10 11:31:45.919251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19efe4a14065'
down_revision = 'fb0f6bf7e0e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_blocked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.drop_column('is_blocked')

    # ### end Alembic commands ###
