"""add phone to creators

Revision ID: 278d0901c23f
Revises: e853a2dd509c
Create Date: 2026-02-10 10:42:46.417721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '278d0901c23f'
down_revision = 'e853a2dd509c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
