"""add page_theme to creators

Revision ID: 2b59a43be6bf
Revises: b8d2f4e6a1c3
Create Date: 2026-02-13 20:42:42.483747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b59a43be6bf'
down_revision = 'b8d2f4e6a1c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_theme', sa.String(length=20), server_default='galactic', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.drop_column('page_theme')

    # ### end Alembic commands ###
