"""Add detailed fee columns to transactions

Revision ID: 4326f5ed1c5e
Revises: 
Create Date: 2025-06-16 13:42:57.905858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4326f5ed1c5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
