"""Add detailed fee columns to transactions

Revision ID: 4326f5ed1c5e
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4326f5ed1c5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Adicionar colunas de taxas detalhadas à tabela transactions
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        # Colunas para valores originais e descontos
        batch_op.add_column(sa.Column('original_amount', sa.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('discount_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True))
        
        # Colunas para taxas detalhadas
        batch_op.add_column(sa.Column('fixed_fee', sa.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('percentage_fee', sa.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('total_fee', sa.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('net_amount', sa.DECIMAL(precision=10, scale=2), nullable=True))
        
        # Colunas para tracking de PIX
        batch_op.add_column(sa.Column('receipt_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('verification_score', sa.DECIMAL(precision=3, scale=2), nullable=True))
        
        # Coluna para session do Stripe
        batch_op.add_column(sa.Column('stripe_session_id', sa.String(length=255), nullable=True))
        
        # Timestamp de reembolso
        batch_op.add_column(sa.Column('refunded_at', sa.DateTime(), nullable=True))
    
    # Adicionar colunas às subscriptions para renovações
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_renewal', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('renewed_from_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('renewed_to_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('removed_at', sa.DateTime(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remover colunas de subscriptions
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('removed_at')
        batch_op.drop_column('renewed_to_id')
        batch_op.drop_column('renewed_from_id')
        batch_op.drop_column('is_renewal')
    
    # Remover colunas de transactions
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('refunded_at')
        batch_op.drop_column('stripe_session_id')
        batch_op.drop_column('verification_score')
        batch_op.drop_column('receipt_hash')
        batch_op.drop_column('net_amount')
        batch_op.drop_column('total_fee')
        batch_op.drop_column('percentage_fee')
        batch_op.drop_column('fixed_fee')
        batch_op.drop_column('discount_percentage')
        batch_op.drop_column('original_amount')
    
    # ### end Alembic commands ###
