"""add custom fee fields to groups table

Revision ID: 744eb6c2d96d
Revises: d71df9a09d0b
Create Date: 2026-02-14 23:13:19.624397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744eb6c2d96d'
down_revision = 'd71df9a09d0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_fixed_fee', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('custom_percentage_fee', sa.Numeric(precision=10, scale=4), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('custom_percentage_fee')
        batch_op.drop_column('custom_fixed_fee')

    # ### end Alembic commands ###
