"""add last_broadcast_at to groups

Revision ID: 7b190646ef2e
Revises: f35ab1ea4a2d
Create Date: 2026-02-10 08:18:24.614740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b190646ef2e'
down_revision = 'f35ab1ea4a2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_broadcast_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('last_broadcast_at')

    # ### end Alembic commands ###
