"""add username_changed_at to creators

Revision ID: ae991a3ef8ef
Revises: 2b59a43be6bf
Create Date: 2026-02-13 21:12:02.094306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae991a3ef8ef'
down_revision = '2b59a43be6bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username_changed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.drop_column('username_changed_at')

    # ### end Alembic commands ###
