"""add google_id to creators table

Revision ID: b3b245cfce4e
Revises: 19efe4a14065
Create Date: 2026-02-10 13:21:10.903039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3b245cfce4e'
down_revision = '19efe4a14065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('uq_creators_google_id', ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.drop_constraint('uq_creators_google_id', type_='unique')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
