"""add system_whitelist_json to groups

Revision ID: cec1733860be
Revises: 2df2e708fdce
Create Date: 2026-02-12 10:07:10.544257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cec1733860be'
down_revision = '2df2e708fdce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_whitelist_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('system_whitelist_json')

    # ### end Alembic commands ###
