"""add anti_leak_enabled to groups

Revision ID: d71df9a09d0b
Revises: 0e7704fc4b29
Create Date: 2026-02-14 21:21:37.387370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd71df9a09d0b'
down_revision = '0e7704fc4b29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anti_leak_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('anti_leak_enabled')

    # ### end Alembic commands ###
