"""add recurring subscription fields

Revision ID: dff1a9331322
Revises: f18a71d11779
Create Date: 2026-02-10 00:01:48.148946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dff1a9331322'
down_revision = 'f18a71d11779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricing_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_product_id', sa.String(length=100), nullable=True))

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cancel_at_period_end', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('payment_method_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('auto_renew', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_legacy', sa.Boolean(), nullable=True))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_invoice_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('billing_reason', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('billing_reason')
        batch_op.drop_column('stripe_invoice_id')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('is_legacy')
        batch_op.drop_column('auto_renew')
        batch_op.drop_column('payment_method_type')
        batch_op.drop_column('cancel_at_period_end')
        batch_op.drop_column('stripe_customer_id')

    with op.batch_alter_table('pricing_plans', schema=None) as batch_op:
        batch_op.drop_column('stripe_product_id')

    # ### end Alembic commands ###
