"""add is_lifetime to pricing_plans

Revision ID: e853a2dd509c
Revises: 7b190646ef2e
Create Date: 2026-02-10 10:10:55.421857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e853a2dd509c'
down_revision = '7b190646ef2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricing_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_lifetime', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricing_plans', schema=None) as batch_op:
        batch_op.drop_column('is_lifetime')

    # ### end Alembic commands ###
