"""Add stripe_session_id to transactions

Revision ID: ec84bdd0add2
Revises: 4326f5ed1c5e
Create Date: 2025-06-17 11:12:14.478647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec84bdd0add2'
down_revision = '4326f5ed1c5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricing_plans', schema=None) as batch_op:
        batch_op.drop_column('features')
        batch_op.drop_column('description')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_subscriptions_telegram_user_id'))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_transactions_payment_id'))
        batch_op.drop_index(batch_op.f('idx_transactions_status'))
        batch_op.drop_index(batch_op.f('idx_transactions_stripe_session_id'))
        batch_op.drop_column('stripe_session_id')
        batch_op.drop_column('payment_id')
        batch_op.drop_column('discount_percentage')
        batch_op.drop_column('original_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_amount', sa.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('discount_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('payment_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('stripe_session_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.create_index(batch_op.f('idx_transactions_stripe_session_id'), ['stripe_session_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_transactions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_transactions_payment_id'), ['payment_id'], unique=False)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_subscriptions_telegram_user_id'), ['telegram_user_id'], unique=False)

    with op.batch_alter_table('pricing_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('features', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
