"""Add auto_renew field to Subscription

Revision ID: f18a71d11779
Revises: ec84bdd0add2
Create Date: 2025-06-17 12:49:23.723087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f18a71d11779'
down_revision = 'ec84bdd0add2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.drop_column('available_balance')
        batch_op.drop_column('pending_balance')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_session_id', sa.String(length=200), nullable=True))
        batch_op.create_index(batch_op.f('ix_transactions_stripe_session_id'), ['stripe_session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_stripe_session_id'))
        batch_op.drop_column('stripe_session_id')

    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_balance', sa.DECIMAL(precision=10, scale=2), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('available_balance', sa.DECIMAL(precision=10, scale=2), server_default=sa.text('0'), nullable=True))

    # ### end Alembic commands ###
