"""add terms acceptance fields to creators

Revision ID: f35ab1ea4a2d
Revises: dff1a9331322
Create Date: 2026-02-10 06:38:57.649263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f35ab1ea4a2d'
down_revision = 'dff1a9331322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terms_accepted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('terms_ip', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('terms_user_agent', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.drop_column('terms_user_agent')
        batch_op.drop_column('terms_ip')
        batch_op.drop_column('terms_accepted_at')

    # ### end Alembic commands ###
